-- ============================================
-- Flyway migration: Insert test data
-- Purpose: populate base data for local/testing
-- ============================================

-- === AREA ===
INSERT INTO areas (id, name, country, city, type)
VALUES ('11111111-1111-1111-1111-111111111111', 'GreenVille', 'Poland', 'Krakow', 'Residential')
ON CONFLICT (id) DO NOTHING;

-- === BUILDINGS ===
INSERT INTO buildings (id, name, country, city, street, number, area_id)
VALUES
    ('22222222-2222-2222-2222-222222222222', 'SkyTower', 'Poland', 'Krakow', 'Lipowa', '12A', '11111111-1111-1111-1111-111111111111'),
    ('33333333-3333-3333-3333-333333333333', 'RiverView', 'Poland', 'Krakow', 'Długa', '9', '11111111-1111-1111-1111-111111111111')
ON CONFLICT (id) DO NOTHING;

-- === USERS ===
-- bcrypt hash for "test" -> $2a$10$DowSDzgVzAuwfFxvR0DkZ.2p58hA2.Zy7Tq.xwB9Xw4/ybdCrKx1O
-- generated by BCryptPasswordEncoder

INSERT INTO users (id, first_name, last_name, email, username, password, user_role, status, building_id)
VALUES
    ('44444444-4444-4444-4444-444444444444', 'Dorian', 'Kowalski', 'jan.kowalski@example.com', 'Dorajn',
     '$2a$10$JBiiTafCTHHYt76EwChHo.7IRICjBwTU8Aqnq/btISa4uMSkiN3Ny',
     'a3f5c9d2-4b8e-4d61-9a67-12c4e9b7f8a1', 'ACTIVE', '22222222-2222-2222-2222-222222222222'),

    ('55555555-5555-5555-5555-555555555555', 'Natalia', 'Nowak', 'anna.nowak@example.com', 'Natalka',
     '$2a$10$JBiiTafCTHHYt76EwChHo.7IRICjBwTU8Aqnq/btISa4uMSkiN3Ny',
     'a3f5c9d2-4b8e-4d61-9a67-12c4e9b7f8a1', 'ACTIVE', '33333333-3333-3333-3333-333333333333'),

    ('66666666-6666-6666-6666-666666666666', 'Piotr', 'Manager', 'piotr.manager@example.com', 'piotr',
     '$2a$10$JBiiTafCTHHYt76EwChHo.7IRICjBwTU8Aqnq/btISa4uMSkiN3Ny',
     'b9e2a7f4-6c1d-47d2-8e93-45ab2c1d3f27', 'ACTIVE', NULL)
ON CONFLICT (id) DO NOTHING;

-- === BUILDINGS MANAGERS ===
INSERT INTO buildings_managers (id, building_id, user_id)
VALUES ('77777777-7777-7777-7777-777777777777', '22222222-2222-2222-2222-222222222222', '66666666-6666-6666-6666-666666666666')
ON CONFLICT (id) DO NOTHING;

-- === FACILITIES ===
INSERT INTO facilities (id, name, building_id, type, capacity, location, requires_approval)
VALUES
    ('88888888-8888-8888-8888-888888888888', 'Fitness Room', '22222222-2222-2222-2222-222222222222', 'GYM', 20, 'Basement', FALSE),
    ('99999999-9999-9999-9999-999999999999', 'Meeting Room', '33333333-3333-3333-3333-333333333333', 'OFFICE', 10, '1st Floor', TRUE)
ON CONFLICT (id) DO NOTHING;
