spring:
  profiles:
    default: dev
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
  mail:
    properties:
      mail.smtp.connectiontimeout: 10000
      mail.smtp.timeout: 10000
      mail.smtp.writetimeout: 10000

server:
  servlet:
    context-path: /v1/api

security:
  enabled: true

storage:
  upload-url-ttl: 15m
  download-url-ttl: 15m
  max-file-size: 50MB
