spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID}
      credentials:
        location: ${GCP_APPLICATION_CREDENTIALS}
  flyway:
    enabled: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: ${MAIL_SMTP_AUTH}
      mail.smtp.starttls.enable: ${MAIL_SMTP_STARTTLS}

server:
  port: ${PORT:8080}

springdoc:
  swagger-ui:
    enabled: false

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_TIME}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_TIME}

storage:
  bucket: ${GCP_BUCKET_NAME}

services:
  chatting:
    url: ${CHATTING_SERVICE_URL}
    apikey: ${CHATTING_API_KEY}

mail:
  from: ${MAIL_FROM}
  from-name: ${MAIL_FROM_NAME}
  locale: ${MAIL_LOCALE}

activation:
  link-base-url: ${ACTIVATION_LINK_BASE_URL}
  token-ttl: ${ACTIVATION_TOKEN_TTL}
