spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
server:
  servlet:
    context-path: /v1/api
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_TIME}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_TIME}

services:
  chatting:
    url: ${CHATTING_SERVICE_URL}
    apikey: ${CHATTING_API_KEY}